package error_message

var (
	ErrProccessingPassword     = "Erro ao processar a senha"
	ErrCreateAccount           = "Erro ao criar a conta"
	ErrUserNotFound            = "Usuário não encontrado"
	ErrWrongPassword           = "Senha incorreta"
	ErrGenerateToken           = "Erro ao gerar o token"
	ErrUpdateAccount           = "Erro ao editar o usuário"
	ErrFindUser                = "Erro ao localizar usuário"
	ErrInvalidToken            = "Token inválido"
	ErrCreateToken             = "Erro na criação do token"
	ErrMethodLogin             = "Método de login inesperado"
	ErrDecodeToken             = "Erro ao decodificar o token"
	ErrCreateRevenue           = "Erro ao criar a receita"
	ErrFindRevenue             = "Erro ao localizar a receita"
	ErrUpdateRevenue           = "Erro ao editar a receita"
	ErrCreateExpense           = "Erro ao criar a despesa"
	ErrFindExpense             = "Erro ao localizar a despesa"
	ErrUpdateExpense           = "Erro ao editar a despesa"
	ErrCreateCategory          = "Erro ao criar a categoria"
	ErrFindCategory            = "Erro ao encontrar a categoria"
	ErrDeleteCategory          = "Erro ao deletar a categoria"
	ErrCreateSaving            = "Erro ao criar a caixinha"
	ErrFindSaving              = "Erro ao localizar a caixinha"
	ErrUpdateSaving            = "Erro ao editar a caixinha"
	ErrDeleteSaving            = "Erro ao deletar a caixinha"
	ErrCreateExpenseFromSaving = "Erro ao adicionar o valor da caixinha as despesas mensais"
	ErrCreateMetric            = "Erro ao criar a métrica"
	ErrFindMetric              = "Erro ao localizar a métrica"
	ErrUpdateMetric            = "Erro ao editar a métrica"
)
